@startuml
class Account {
  +id
  +name
  +type
  +currentBalance
  +status
}

class Movement {
  +id
  +type
  +status
  +amount
  +period
  +sourceType
}

class Category {
  +id
  +type
  +name
}

Account "1" --> "0..*" Movement
Category "1" --> "0..*" Movement
@enduml

